Homework21: Andrei Kulbitski
kulbitski-andrei/Homeworks pull request #18
Opened 2024-07-19 07:59 UTC by kulbitski-andrei

pytests for bank_module.py, library_module.py
fixed logging (moved to separate file)
reports added

2024-07-20 19:43 UTC, Stml89 requested changes

2024-07-20 19:43 UTC, Stml89 commented on homework_21/report_21_2.html
Log report should be in the `.gitignore`

2024-07-20 19:43 UTC, Stml89 commented on homework_21/report_21_1.html
Log report should be in the `.gitignore`

2024-07-20 19:43 UTC, Stml89 commented on log_dir/log_setup.py
> +logger.setLevel(logging.DEBUG)
Requirements says: "Есть возможность запустить тесты с разным уровнем логгирования без изменения кода(те передача уровня логгирования во время запуска тестов)"

2024-07-24 11:28 UTC, kulbitski-andrei commented on homework_21/report_21_2.html
Done

2024-07-24 11:28 UTC, kulbitski-andrei commented on homework_21/report_21_1.html
Done

2024-07-26 11:26 UTC, kulbitski-andrei commented on log_dir/log_setup.py
> +logger.setLevel(logging.DEBUG)
Not sure I completely understand what's needed. I use command:
pytest --log-cli-level=WARNING <pat_to_file>
and logs are displayed correctly, according to chosen level of logging. Please see attached screenshots:
![image](https://github.com/user-attachments/assets/2a2cc6db-cc43-4b23-8b9d-f8ab228fe98d)
![image](https://github.com/user-attachments/assets/be87a88e-7e33-4682-810e-f9f8ef4036f0)
![image](https://github.com/user-attachments/assets/d782c04e-6e45-479d-a413-0da86657ce50)

The logger and handler above just provide "default" level. But this default level is overrided by the level user chooses while running a test with console command.

2024-07-27 16:55 UTC, Stml89 approved these changes

2024-07-27 16:55 UTC, Stml89 commented on .gitignore
> +/report.html
assets/
*.css
*.html
*.xml

2024-07-27 16:55 UTC, Stml89 commented on homework_21/report_21_1.html
should be in `.gitignore`

2024-07-27 16:55 UTC, Stml89 commented on homework_21/report_21_2.html
should be in `.gitignore`

2024-07-27 16:55 UTC, Stml89 commented on homework_21/test_homework_21_1.py
> +    log_setup.logger.warning("LOGGER WARNING MESSAGE: Test passed")
No need to use all log levels, enough INFO
```suggestion
    log_setup.logger.info("LOGGER INFO MESSAGE: Test passed")
```
and fix for other TCs

2024-07-31 13:05 UTC, merged