Homework24: Andrei Kulbitski
kulbitski-andrei/Homeworks pull request #22
Opened 2024-08-03 08:28 UTC by kulbitski-andrei

Homework 24 

Known issues:
- fixtures not yet moved to conftest
- some pylints were disabled because of the lack of time

Plan to fix those issues in Homework 25

2024-08-04 12:22 UTC, Stml89 requested changes

2024-08-05 07:31 UTC, kulbitski-andrei commented on homework_24/tests/tests.py
> +    time.sleep(1)
Sorry, forgot to remove those time.sleeps() :)

2024-08-05 13:01 UTC, kulbitski-andrei commented on homework_24/tests/tests.py
> +    time.sleep(1)
Fixed

2024-08-10 06:52 UTC, Stml89 approved these changes

2024-08-15 11:05 UTC, merged